# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

embeddings_verse <- function(dgrmatrix_p, dgrmatrix_j, n_epochs = 100000L) {
    .Call('_deepwalker_embeddings_verse', PACKAGE = 'deepwalker', dgrmatrix_p, dgrmatrix_j, n_epochs)
}

