# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

embeddings_verse_pagerank <- function(dgrmatrix_p, dgrmatrix_j, dimension = 128L, epochs = 100000L, learning_rate = 0.0025, samples = 3L, alpha = 0.85, threads = 1L) {
    .Call('_deepwalker_embeddings_verse_pagerank', PACKAGE = 'deepwalker', dgrmatrix_p, dgrmatrix_j, dimension, epochs, learning_rate, samples, alpha, threads)
}

